esphome:
  name: <device name>
  friendly_name: <friendly name>
  min_version: 2024.6.0
  platformio_options:
    # Run CPU at 160Mhz to fix mhi_ac_ctrl_core.loop error: -2
    board_build.f_cpu: 160000000L

esp8266:
  board: d1_mini

logger:
  level: INFO
  baud_rate: 0

ota:
  - platform: esphome
    password: <pass here>

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: <hotspot name>
    password: <hotspot pass>

captive_portal:

api:
  encryption:
    key: <your key here>

external_components:
  - source: github://ginkage/MHI-AC-Ctrl-ESPHome@master
    components: [MhiAcCtrl]

# Version 4.0
MhiAcCtrl:
  # Only 20 (legacy) or 33 (includes 3D auto and vertical vanes) possible.
  # If you encounter mhi_ac_ctrl_core.loop error: -2 errors, change the frame_size to 20
  frame_size: 33

globals:
  - id: grid_voltage
    type: int
    restore_value: no
    initial_value: "230"

climate:
  - platform: MhiAcCtrl
    name: "MHI Air Conditioner"
    on_control:
      - logger.log: "Control input received; power updated!"
      - sensor.template.publish:
          id: power
          state: 0
sensor:
  - platform: MhiAcCtrl
    current_power:
      name: "Current power"
      id: ac_current_power
      on_value:
        then:
          - sensor.template.publish:
              id: power
              state: !lambda "return id(ac_current_power).state * id(grid_voltage);"
  - platform: template
    name: MHI - Current Power
    id: "power"
    unit_of_measurement: W
    icon: mdi:lightning-bolt
  - platform: total_daily_energy
    name: "MHI - Daily Energy"
    power_id: "power"
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
      - throttle: 300s
    unit_of_measurement: kWh
    method: left
    icon: mdi:lightning-bolt
select:
  - platform: MhiAcCtrl
    vertical_vanes:
      name: Fan Control Up Down
    horizontal_vanes:
      name: Fan Control Left Right

switch:
  - platform: MhiAcCtrl
    vanes_3d_auto:
      name: "3D Auto"
